version: '3.3'

services:
    db:
        image: wachira90/mysql:5.7.23
        container_name: db
        restart: always
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_USER: wachira
            MYSQL_PASSWORD: wachira
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: testdb
        ports:
            - 3306:3306

    adminer:
        image: wachira90/adminer:4.7.8
        container_name: adminer
        restart: always
        links:
            - db
        ports:
            - 8080:8080

volumes:
    db_data:
